### ISSUE TITLE
[Bug]: Docker container SSE not working

### ISSUE THREAD

**Issue by Bramzor** [sooperset/mcp-atlassian#291]
### Prerequisites

- [x] I have searched the [existing issues](https://github.com/sooperset/mcp-atlassian/issues) to make sure this bug has not already been reported.
- [x] I have checked the [README](https://github.com/sooperset/mcp-atlassian/blob/main/README.md) for relevant information.

### Bug Description

I'm trying to get this MCP Server working with n8n. But got `Error in sub-node ‘MCP Client‘
Could not connect to your MCP server` when I try to connect.

n8n logs:
```
n8n-1          | McpClientTool: Failed to connect to MCP Server
n8n-1          | Error in sub-node MCP Client
n8n-1          | McpClientTool: Failed to connect to MCP Server
n8n-1          | Error in sub-node MCP Client
n8n-1          | McpClientTool: Failed to connect to MCP Server
n8n-1          | Error in sub-node MCP Client
```

Tried using:
http://172.19.0.6:8000/sse
http://atlassian:8000/sse
http://PRIVATEIP:8000/sse
And lots of other possibilities.

In docker compose I'm using:

```
  atlassian:
    image: mcp/atlassian
    ports:
      - ${PRIVATEIP}:8000:8000  # Expose port 8000 on the host and map it to port 8000 in the container
    environment:
      - MCP_VERBOSE=true
      - MCP_VERY_VERBOSE=true
      - TRANSPORT=sse
      - PORT=8000
    env_file:
      - ./.env.atlassian  # Load environment variables from this file
    stdin_open: true
```

I don't see any logs on the atlassian container. Probably because of the stdin_open option (which is for stdio functionality I assume?). If I comment that line the container just exists.

### Steps to Reproduce

Run it using docker (or docker compose) and try to connect to it over SSE.

### Expected Behavior

I would like to see something in the container logs that shows what might be going wrong. Because now It's try and error every single option to see if something changes.

### Actual Behavior

```shell
n8n logs:

n8n-1          | McpClientTool: Failed to connect to MCP Server
n8n-1          | Error in sub-node MCP Client
n8n-1          | McpClientTool: Failed to connect to MCP Server
n8n-1          | Error in sub-node MCP Client
n8n-1          | McpClientTool: Failed to connect to MCP Server
n8n-1          | Error in sub-node MCP Client
```

### mcp-atlassian Version

latest docker release

### Installation Method

Docker

### Operating System

Linux (Specify distribution below if relevant)

### Python Version

not sure

### Atlassian Instance Type

Jira Cloud

### Client Application

n8n

**Comment by sooperset** [comment]
Hi @Bramzor,

Thanks for the detailed issue report and providing the logs.

I've run the `mcp-atlassian` container locally using Docker with the SSE transport enabled, similar to your setup:

```bash
docker run --rm --name mcp-atlassian-test \
  -p 127.0.0.1:9000:9000 \
  --env-file .env.atlassian \
  mcp-atlassian-local \
  --transport sse --port 9000 -vv
```

![Image](https://github.com/user-attachments/assets/448205f7-4789-4419-a8c2-fb99570e4196)

Based on my testing using both `curl` and another MCP client (Cursor IDE connected to the container):

1.  The server starts correctly and listens on the specified port for SSE connections.
2.  Connecting via `GET /sse` works, and the server sends back the initial `event: endpoint` message with the `/messages/` URL and session ID, followed by periodic pings (as seen in your `curl` test and mine).
3.  Sending MCP requests (like `tools/list`) via `POST` to the `/messages/` endpoint (using the session ID from the `endpoint` event) is successful.
4.  The server processes these requests and sends the corresponding responses back over the original `/sse` connection as `event: message`.

This indicates that the server's core SSE functionality (handshake, message posting, response streaming) appears to be working correctly within the Docker container when interacting with standard tools and another MCP client.

Regarding the container exiting: the `stdin_open: true` option in your Docker Compose is intended for the `stdio` transport. For SSE, the `uvicorn` web server should keep the container running without this option. Please try removing `stdin_open: true` from your configuration. If the container *still* exits immediately when using `--transport sse`, please let us know, as that might indicate a different issue.

Given that the server works with `curl` and the Cursor IDE client, the connection problem you're experiencing with `n8n` is likely related to factors external to this server code, possibly:

*   **Networking:** Ensure the `n8n` container can reach the `mcp-atlassian` container on the correct port within your Docker network setup. If using Docker Compose, try connecting from `n8n` to `http://atlassian:8000/sse` (using the service name). If connecting from outside the Docker network, ensure you're using the correct host IP and exposed port (e.g., `http://[YOUR_PRIVATE_IP]:8000/sse`).
*   **`n8n` Configuration:** Double-check the exact URL and configuration within the `n8n` MCP Client node.

While debugging `n8n` itself is outside the scope of this repository, hopefully, checking the network path and client configuration helps resolve the connection issue.

**Comment by Bramzor** [comment]
@sooperset Thanks for testing. Think I found the issue.

The example .env file (https://github.com/sooperset/mcp-atlassian/blob/main/.env.example)  mentions the following configurations lines:

```
# TRANSPORT=stdio
# PORT=8000
```

Based on this, I assumed that changing these values to TRANSPORT=sse and a valid port, that it would enable SSE.

```
TRANSPORT=sse
PORT=8000
```

But it seems these environment variables are ignored?

``` 
 docker run --rm --name mcp-atlassian-test   -p 127.0.0.1:9000:9000   --env-file mcp/.env.atlassian   mcp/atlassian -vv
DEBUG - mcp-atlassian - Attempting to load environment from default .env file
DEBUG - mcp.server.lowlevel.server - Initializing server 'mcp-atlassian'
DEBUG - mcp.server.lowlevel.server - Registering handler for ListResourcesRequest
DEBUG - mcp.server.lowlevel.server - Registering handler for ReadResourceRequest
DEBUG - mcp.server.lowlevel.server - Registering handler for ListToolsRequest
DEBUG - mcp.server.lowlevel.server - Registering handler for CallToolRequest
DEBUG - asyncio - Using selector: EpollSelector
INFO - mcp-atlassian - Using Confluence Cloud authentication method
INFO - mcp-atlassian - Using Jira Cloud authentication method
INFO - mcp-atlassian - Starting MCP Atlassian server
INFO - mcp-atlassian - Read-only mode: DISABLED
INFO - mcp-atlassian - Confluence URL: https://your-domain.atlassian.net/wiki
INFO - mcp-atlassian - Jira URL: https://your-domain.atlassian.net
``` 
The above just exits the container so I assume it's still expecting stdio ?

It is only after specifying --transport sse directly like you did that it does work:

``` 
docker run --rm --name mcp-atlassian-test   -p 127.0.0.1:9000:9000   --env-file mcp/.env.atlassian   mcp/atlassian  --transport sse --port 9000 -vv
DEBUG - mcp-atlassian - Attempting to load environment from default .env file
DEBUG - mcp.server.lowlevel.server - Initializing server 'mcp-atlassian'
DEBUG - mcp.server.lowlevel.server - Registering handler for ListResourcesRequest
DEBUG - mcp.server.lowlevel.server - Registering handler for ReadResourceRequest
DEBUG - mcp.server.lowlevel.server - Registering handler for ListToolsRequest
DEBUG - mcp.server.lowlevel.server - Registering handler for CallToolRequest
DEBUG - asyncio - Using selector: EpollSelector
DEBUG - mcp.server.sse - SseServerTransport initialized with endpoint: /messages/
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
``` 

So in order for it to work, I had the add `command: ["--transport", "sse"]` to the docker compose file. Specifying this using the environment variables simply does not work.

```
  atlassian:
    image: mcp/atlassian
    ports:
      - 8000:8000
    environment:
      - MCP_VERBOSE=true # Does not provide any output if transport method is not set to sse?
      - MCP_VERY_VERBOSE=true # Does not provide any output if transport method is not set to sse?
      - TRANSPORT=sse # Does not work
      - PORT=8000
    env_file:
      - .env.atlassian  # Load environment variables from this file (TRANSPORT does not work)
    command: ["--transport", "sse", "--port", "9000"]
```

I assume this is a bug that the TRANSPORT setting in the .env file or as an environment parameter are both ignored?
