### ISSUE TITLE
[Feature]: Add health checks for SSE transport when deploying in a K8s environment.

### ISSUE THREAD

**Issue by tmoreira2020** [sooperset/mcp-atlassian#359]
### Is your feature request related to a problem? Please describe.

hey there, I'm trying to deploy the MCP on a K8s environment but it fails to detect a health status because SSE doesn't close the connection.

### Describe the solution you'd like

Is it possible to add an endpoint so my probes can check if the service is up and running with SSE? ChatGPT agrees with this approach! 😄 https://chatgpt.com/share/6813b37f-fcc8-8005-910d-f067952208c6

Thank you!

**Comment by JeongsikKang** [comment]
@sooperset First of all, thank you for creating such a great project. 
@tmoreira2020  I agree with you. Using SSE for k8s probes seems quite difficult.
It would be great if a page like /healthz could be provided for monitoring purposes.
For now, I'm running it without any probe checks.

@sooperset 좋은 프로젝트 만들어 주셔서 고맙습니다. 
@tmoreira2020 공감합니다. sse를 k8s probe로 사용하는 것은 어려울 것 같아 보입니다. /healtz와 같은 페이지가 모니터링 용도로 제공되면 좋을 것 같습니다. 저는 probe 검사를 일단 제외하고 사용하고 있습니다. 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-atlassian
  labels:
    app: mcp-atlassian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-atlassian
  template:
    metadata:
      labels:
        app: mcp-atlassian
    spec:
      containers:
        - name: mcp-atlassian
          image: ghcr.io/sooperset/mcp-atlassian:0.9
          env:
          - name: JIRA_URL
            value: "some_url"
          - name: JIRA_USERNAME
            value: "some_user"
          - name: JIRA_PERSONAL_TOKEN
            value: "some_token"
          args:
          - "--transport"
          - "sse"
          - "--port"
          - "8080"
          - "-vv"
          ports:
            - containerPort: 8080
          #readinessProbe:
          #  httpGet:
          #    path: /healtz
          #    port: 8081
          #  initialDelaySeconds: 5
          #  periodSeconds: 10
          #livenessProbe:
          #  httpGet:
          #    path: /healtz
          #    port: 8081
          #  initialDelaySeconds: 15
          #  periodSeconds: 20
```
